language: node_js
node_js:
  - "lts/*"
install:
  - npm install
branches:
  only:
    - "ftr/*"
jobs:
  include:
    - stage: "Build"
      name: "Build lib"
      script: npm run build --if-present
    - stage: "test" # naming the test stage
      name: "Unit Test" # names the first Tests stage job
      script: npm test
