language: node_js
node_js:
  - "lts/*"
install:
  - npm install
branches:
  only:
    - dev
jobs:
  include:
    - stage: "Build"
      name: "Build lib"
      script: npm run build --if-present
    - stage: "Tests" # naming the Tests stage
      name: "Unit Tests" # names the first Tests stage job
      script: npm test
