language: node_js
node_js:
  - "lts/*"
install:
  - npm i
git:
  depth: 2
branches:
  only:
    - dev
jobs:
  include:
    - stage: "Tests" # naming the Tests stage
      name: "Unit Tests" # names the first Tests stage job
      script: npm test

before_script:
  - npm install -g gulp-cli
script: gulp
