# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      # Use Tehran Standard Time
      timezone: "Asia/Tehran"
      # Labels on pull requests for security and version updates
      labels:
        - "npm dependencies"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Use Tehran Standard Time
      timezone: "Asia/Tehran"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # Use Tehran Standard Time
      timezone: "Asia/Tehran"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Use Tehran Standard Time
      timezone: "Asia/Tehran"
