name: Publish Packages to GitHub Packages And NPMJS
on:
  push:
    branches: [main]
    tags:
      - "*.*.*"
  pull_request:
    branches: [main]
  release:
    types: [published]
# env:
#   NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
#   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  tests-pkgs: #TEST Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies & test
        shell: bash
        run: |
          npm install
          npm run build --if-present
          npm test

  publish-npmjs-pkgs: #NPM Packages
    needs: tests-pkgs
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to NPM Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          # scope: "@md-akhi"
          always-auth: true
      - name: Removed Docs File
        uses: JesseTG/rm@v1.0.3
        with:
          path: docs
      - name: Install dependencies & publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        shell: bash
        run: |
          npm install
          npm run build --if-present
          npm publish --access public
      # Setup .npmrc file to publish to NPM Packages
      # With Scop
      # - name: Set package registry
      #   run: npm config set @md-akhi:registry https://registry.npmjs.org/
      # WithOut Scop
      # - name: Set package registry without -scope
      #   run: npm config set registry=https://registry.npmjs.org
      # - name: Npm registry authentication
      #   run: npm set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      # - run: |
      #     npm publish --access public

  publish-gitHub-pkgs: #GitHub Packages
    needs: tests-pkgs
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@md-akhi"
          always-auth: true
      - name: Removed Docs File
        uses: JesseTG/rm@v1.0.3
        with:
          path: docs
      - name: Install dependencies & publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        shell: bash
        run: |
          npm install
          npm pkg set name="@md-akhi/shdate"
          npm run build
          npm publish
      # Setup .npmrc file to publish to GitHub Packages
      # With Scop
      # - name: Set package registry with -scope
      #   run: npm config set @md-akhi:registry=https://npm.pkg.github.com
      # WithOut Scop
      # - name: Set package registry without -scope
      #   run: npm config set registry=https://npm.pkg.github.com/
      # - name: Github package registry authentication
      #   run: npm set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
      # - run: |
      #     npm pkg set name="@md-akhi/shdate"
      #     npm publish
        env:
          GITHUB_TOKEN: $GITHUB_TOKEN

  publish-docker: # Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_TOKEN
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: $DOCKER_HUB_USERNAME/shdatetime:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_USERNAME
          password: $GITHUB_TOKEN
          tags: ghcr.io/${{ github.repository_owner }}/shdatetime:latest
        env:
          DOCKER_HUB_TOKEN: $DOCKER_HUB_TOKEN
          DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME
          GITHUB_TOKEN: $GITHUB_TOKEN
          GITHUB_USERNAME: $GITHUB_USERNAME
